
/**
 * FreeIMU calibration header. Automatically generated by FreeIMU_GUI.
 * Do not edit manually unless you know what you are doing.
*/


#define CALIBRATION_H

const int acc_off_x = -16;
const int acc_off_y = -1;
const int acc_off_z = 34;
const float acc_scale_x = 252.718094;
const float acc_scale_y = 262.757180;
const float acc_scale_z = 255.089549;

const int magn_off_x = -4;
const int magn_off_y = -15;
const int magn_off_z = 60;
const float magn_scale_x = 481.067489;
const float magn_scale_y = 482.541427;
const float magn_scale_z = 481.942454;
